All: true
transaction_pool_input_throughput: true
net_p2p_transmission_latency: true
peer_message_throughput: true
db_state_write_rate: true 
tx_queue_delay: true
block_commit_duration_start: true
block_commit_duration_end: true
block_validation_efficiency_start: true
block_validation_efficiency_end: true
tx_delay_start: true 
tx_delay_end: true
block_tx_conflict_rate: true
contract_execute_efficiency: true
consensus_tbft_cost: true
consensus_tbft_proposal_start: true
consensus_tbft_proposal_end: true
db_state_read_rate: false
Cpumem: false